StAdvAttack:
  start: 0
  end: 0.1
  step: 0.005
ReColorAdvAttack:
  start: 0
  end: 0.1
  step: 0.005
JPEGLinfAttack:
  start: 0
  end: 0.2
  step: 0.01
JPEGL1Attack:
  start: 0
  end: 20
  step: 1
ElasticAttack:
  start: 0
  end: 1
  step: 0.05
LinfAttack:
  start: 0
  end: 0.1
  step: 0.005
L2Attack: 
  start: 0
  end: 2.5
  step: 0.125
L1Attack: 
  start: 0
  end: 30
  step: 1.5
LPIPSAttack: 
  start: 0
  end: 0.5
  step: 0.025
