StAdvAttack:
  start: 0
  end: 0.1
  step: 0.005
ReColorAdvAttack:
  start: 0
  end: 0.1
  step: 0.005
JPEGLinfAttack:
  start: 0
  end: 0.2
  step: 0.01
JPEGL1Attack:
  start: 0
  end: 20
  step: 1
ElasticAttack:
  start: 0
  end: 1
  step: 0.05
LinfAttack:
  start: 0
  end: 0.1
  step: 0.005
L2Attack: 
  start: 0
  end: 2.5
  step: 0.125
L1Attack: 
  start: 0
  end: 30
  step: 1.5
FastLagrangePerceptualAttack: 
  start: 0
  end: 0.5
  step: 0.025
Hue:
  start: 0
  end: 0.5
  step: 0.025
Saturation:
  start: 0
  end: 0.5
  step: 0.025
Brightness:
  start: 0
  end: 0.3
  step: 0.015
Contrast:
  start: 0
  end: 0.5
  step: 0.025
SnowAttack:
  start: 0
  end: 0.1
  step: 0.005
FogAttack:
  start: 0
  end: 50
  step: 2.5
GaborAttack:
  start: 0
  end: 10
  step: 0.5
AffineWarp:
  start: 0
  end: 0.1
  step: 0.005
PerspectiveWarp:
  start: 0
  end: 0.002
  step: 0.0001
